Update main for AWS deployment
scalableinternetservices/cradio pull request #37
Opened 2020-11-27 21:59 UTC by danieljaffe

General code review before AWS deployment of main.

2020-11-27 22:40 UTC, dbreon88 commented on server/src/graphql/api.ts
> +     check(await entityManager.increment(ListeningSession, { id: listeningSessionId }, "queueLength", 1))
this may lead to a race condition at high loads, will look into this for future pushes

2020-11-27 22:41 UTC, dbreon88 approved these changes
merge to main looks good

2020-11-27 23:29 UTC, aybeshlikyan requested changes
Looks good! I commented on all the console.logs that should be commented out before we merge.

2020-11-27 23:29 UTC, aybeshlikyan commented on server/src/graphql/api.ts
> +    console.log("result", result)
comment out the console.log

2020-11-27 23:29 UTC, aybeshlikyan commented on web/src/view/page/HomePage.tsx
> +    console.log("in join session")
remove console.log

2020-11-27 23:29 UTC, aybeshlikyan commented on web/src/view/page/HomePage.tsx
> +  console.log("sessionID from state", sessionID)
remove console.log

2020-11-27 23:29 UTC, aybeshlikyan commented on web/src/view/page/HomePage.tsx
> +    console.log("data.listeningsession", data.listeningSession)
remove console.log

2020-11-27 23:29 UTC, aybeshlikyan commented on web/src/view/page/LecturesPage.tsx
> +  console.log('LecturesPages')
remove console.log

2020-11-27 23:29 UTC, aybeshlikyan commented on web/src/view/page/LecturesPage.tsx
> +  console.log(idSession)
comment out these console.logs

2020-11-27 23:29 UTC, aybeshlikyan commented on web/src/view/page/LecturesPage.tsx
> +  console.log(sessionData)
comment out console.log

2020-11-27 23:29 UTC, aybeshlikyan commented on web/src/view/page/LecturesPage.tsx
> +                        console.log(currSong)
comment out console.log

2020-11-27 23:29 UTC, aybeshlikyan commented on web/src/view/playground/Surveys.tsx
> +  console.log(data)
comment out console.log

2020-11-28 05:45 UTC, danieljaffe reviewed
All console.log in these 25 files have been commented out. Dylan's comment not resolved for this merge.

2020-11-28 05:53 UTC, merged